# -*- coding: utf-8 -*-
"""Cópia de Exercícios montados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvowLztZLM5QhGj_OgxfXhVNdI1uaq4M
"""

#faça um programa que peça ao usuario a distancia de sua casa ate o local de trabalho(em metros) e verifique se a distancia for maior que 10km. Se sim, imprima: "a distancia é maior que 10km." Se não,imprima: "a distancia é menor que 10km."
distancia = float(input("Digite a distacia da sua casa ate o local de trabalho(em metros): "))
if distancia > 10000:
  print("A distancia é maior que 10km.")
else:
  print("A distancia é menor que 10km.")

#faça um programa que peça dois numeros inteiros e calcule a divisao de um numero pelo outro, verifique se o resultado possui resto. Se sim, mostre o resto da divisao, se não mostre apenas o resultado da divisão.
numero = int(input("Digite o primeiro numero: "))
numero2 = int(input("Digite o segundo numero: "))
resultado = numero/numero2
resto = numero % numero2
if resto != 0:
  print(f"O resultado da divisão é {resultado:.2f} e o resto é {resto}")
else:
  print(f"O resultado da divisão é {resultado:.2f}")

#Faça um programa que peça 5 numeros inteiros entre 1 e 5 (podendo inclusive ser 1 ou 5 e podendo repetir os numeros) e calcule a soma e a mutiplicação deles. imprima todos os resultados obtidos dos calculos.
soma = 0
multiplicacao = 1
for i in range(5):
  numero = int(input(f"Digite o {i+1}º numero inteiro entre 1 e 5: "))
  soma += numero
  multiplicacao *= numero
  if numero < 1 or numero > 5:
   print("Numero invalido")
   break
else:
 print()
 print(f"O resultado da soma é: {soma} \nO resultado da multiplicação é: {multiplicacao}")