# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

1- Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor valido: "))
print("Sucesso")

"""2-Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

nome = input("Insira o nome de usuário: ")
senha = input("Insira a senha: ")
while senha == nome:
  print("Erro")
  nome = input("Insira o nome de usuário novamente: ")
  senha = input("Insira a senha novamente: ")
print("Usuário e senha corretos")

"""3-Escreva um programa que conte de 1 a 10 e imprima cada número."""

numero = 1
while numero <= 10:
  print(numero)
  numero += 1

"""4-Escreva um programa que imprima os números pares de 1 a 20."""

numero = 2
while numero <= 20:
  print(numero)
  numero += 2

"""5-Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("Digite um numero: "))
contador = 1
while contador <= numero:
  print(contador)
  contador += 1

"""6-Escreva um programa que solicite ao usuário que insira um número e, em seguida, imprima todos os números pares de 2 até esse número.

"""

numero = int(input("Digite um numero: "))
contador = 2
while contador <= numero:
  print(contador)
  contador += 2

"""7-Escreva um programa que solicite ao usuário que insira um número e, em seguida, imprima a tabuada desse número até 10.

"""

numero = int(input("Por favor,digite um numero: "))
contador = 1
while contador <= 10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador += 1

"""8-Escreva um programa que solicite ao usuário que insira uma senha. O programa deve continuar solicitando a senha até que o usuário insira a senha correta."""

senha_correta = "1234"
senha = input("Digite uma senha: ")
while senha != senha_correta:
 print("Senha incorreta")
 senha = input("Digite uma senha valida: ")
print("Senha correta")

"""9-Escreva um programa que calcule a média de uma lista de números fornecida pelo usuário.

"""

numeros = int(input("Digite um numero: "))
contador = 0
soma = 0
while contador < 5:
  numeros = int(input("Digite mais um numero: "))
  contador += 1
  soma += numeros
  media = soma/contador
print(f"A media dos numeros é {media}")

"""10-Escreva um programa que solicite ao usuário que insira números até que ele insira o número 0. Em seguida, imprima a soma de todos os números inseridos."""

numero = float(input("Insira um numero: "))
soma = 0
while numero != 0:
  numero = float(input("Insira outro numero: "))
  soma += numero
print(f"A soma dos numeros que foram diferente de 0 é igual a {soma}")

"""11-Escreva um programa que solicite ao usuário que insira números até que ele insira um número negativo. Em seguida, imprima o maior número inserido."""

maior_numero = 0
numero = float(input("Insira um número: "))
while numero >= 0:
    numero = float(input("Insira outro numero: "))
    if numero < 0:
     break
    elif numero > maior_numero:
      maior_numero = numero
print("O numero insirido é um numero negativo")
print(f"O maior número inserido é: {maior_numero}")