# -*- coding: utf-8 -*-
"""Exercicios corrigidos (for)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnvStkdG14_7CRYuDXpbnHbXC2QbFPqB
"""

maior_numero = float('-inf')
for i in range(5):
  numero = int(input(f"Digite o {i+1}º numero: "))
  if numero > maior_numero:
    maior_numero = numero
print(f"O maior numero digitado é: {maior_numero}")

for numero in range(1000,2001):
  if numero % 11 == 2:
    print(numero)

soma = 0
for i in range(5):
  numero = float(input(f"Digite o {i+1}º numero: "))
  soma += numero
  media = soma/5
print(f"A soma dos numeros é: {soma}")
print(f"A media dos numeros é: {media}")

numero = int(input("Digite um numero para ver sua tabuada: "))
print(f"******** Tabuada do numero {numero} ********")

for i in range(1,11):
  resultado = numero * i
  print(f"{numero} x {i} = {resultado}")

for i in range(1,11):
  for j in range(1,11):
    print()
    print(f"{i} x {j} = {i * j}")

for i in range(1,21):
  print(i)
print()
print(list(range(1,21)))

for i in range(1,51,2):
  print(i)
  # outro jeito: if i % 2 != 0:

#8. Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.
num1 = int(input("Digite o 1º numero inteiro: "))
num2 = int(input("Digite o 2º numero inteiro: "))
if num2 > num1:
 for numero in range(num1, num2, 1):
  print(numero)

lojaB = 54000
lojaA = 0

for cliente in range(5):
  gasto = float(input(f"Digite o valor gasto do cliente {cliente+1} "))
  lojaA += gasto

if lojaA > lojaB:
 print(f"A loja A superou o faturamento da loja B com um valor arrecadado maior de R${lojaA - lojaB}")
elif lojaB > lojaA:
  print(f"A loja B superou o faturamento da loja A com um valor arrecadado maior de R${lojaB - lojaA}")
else:
  print("As duas lojas arrecadaram o mesmo valor de R$54000")

#10. Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.
par = 0
impar = 0
for i in range(10):
  numero = int(input(f"Digite o {i+1}º numero: "))
  if numero % 2 == 0:
     par += 1
  else:
     impar += 1
print(f"Numeros pares: {par}")
print(f"Numeros impares: {impar}")

# recebe aumento anualmente
# foi contratado em 1995
# salario inicial de 1000
# em 1996 recebeu 1,5%
# em 97 (inclusive) dobro do ano anterior %

salario = float(input("Digite o salario inicial do funcionario: "))
percentual = 0.015

for i in range(1996,2025):
  aumento = salario * percentual
  salario += aumento
  percentual *= 2
  print(f"Salario em {i} = {salario:.2f}")

#12. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
for t in range(99999):
  nota = int(input(f"Digite uma nota entre zero e dez: "))
  if nota >= 0 and nota <= 10:
   print(f"Nota valida: {nota}")
   break
  else:
   print(f"Nota invalida.")

valor = float(input("Digite o valor da compra: "))
contagem = 1 # inicia a variavel de contagem com valor 1

if valor >= 600 and contagem: # verifica se o valor da compra é maior que 600 e se a contagem é diferente de zero
#o que sempre sera verdadeiro, pois a contagem comeca com 1
  reduzido = valor - 500 # calcula o valor reduzido subtraindo 500 do valor da compra
  if reduzido >= 100 or contagem <= 24: # vifica se o valor reduzido é maior ou igual a 100 ou se a contagem é menor ou igual a 24
   for x in range(999): # loop que itera 999 vezes
    contagem += 1 # incrementando a contagem
    reduzido -= 100 # reduz o valor em R$100
    if reduzido < 100 or contagem == 24: # verifica se o valor reduzido é menor que R$100 ou se a contagem é igual a 24
     break # sai do loop

porcentagem = contagem/100
desconto = valor * porcentagem
final = valor - desconto
print(f"O produto de R${valor:.2f} ficará a partir de R${final} com {contagem:.0f}% de desconto")

ate15 = 0
de16a30 = 0
de31a45 = 0
de46a60 = 0
mais60 = 0

for pessoa in range(15):
  idade = int(input(f"Digite a idade da pessoa {pessoa+1}ª: "))
  if idade <= 15:
    ate15 += 1
  elif idade <= 30:
    de16a30 += 1
  elif idade <= 45:
    de31a45 += 1
  elif idade <= 60:
    de46a60 += 1
  else:
    mais60 += 1

print()
print("Quantidade de pessoas em cada faixa etária:")
print(f"Até 15 anos: {ate15}")
print(f"De 16 a 30 anos: {de16a30}")
print(f"De 31 a 45 anos: {de31a45}")
print(f"De 46 a 60 anos: {de46a60}")
print(f"Acima de 61 anos: {mais60}")
print()
print(f"{((100 * ate15)/15):.2f}% das pessoas até 15 anos")
print(f"{((100 * mais60)/15):.2f}% das pessoas tem mais de 60 anos")

base = int(input("Digite o valor da base: "))
expoente = int(input("Digite o valor do expoente: "))
resultado = 1

for i in range(expoente):
  if base == 1:
    resultado = base
  else:
    resultado *= base
print(f"Resultado {resultado}")

n = int(input("Digite um numero: "))
for numerotestado in range(1,n+1):
  for numerodivisor in range(numerotestado):
    print(f"{numerotestado}/{numerodivisor+1} = {numerotestado%(numerodivisor+1)}")
    if numerotestado % (numerodivisor+1) == 0:
      if 1 != numerodivisor+1 != numerotestado:
        print("Não é primo")
        break
      elif numerodivisor+1 == numerotestado:
        print("É primo")