# -*- coding: utf-8 -*-
"""Atividades (if,else,elif)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLZlFIOiGMe6XEMR2QFsdH-2x4KxNvvg
"""

numero = int(input("Digite um numero "))
if numero > 0:
 print("O numero é positivo")
else:
 print("O numero é negativo")

sexo = input("Digite M para masculino ou F para feminino: ")
if sexo == "F":
  print("Sexo feminino")
elif sexo == "M":
  print("Sexo masculino")
else:
  print("Sexo inválido")

letra = input("Digite uma letra ")
if letra == "a" or letra == "e" or letra == "i" or letra == "o" or letra == "u":
  print("É uma vogal")
else:
  print("Não é uma vogal")

parcial1 = int(input("insira a nota da primeira parcial "))
parcial2 = int(input("insira a nota da segunda parcial "))
media = (parcial1 + parcial2)/2
if media == 10:
 print("Aprovado com distinção")
elif media >= 7:
  print("Aprovado")
else:
  print("Reprovado")

a = (input("insira o primeiro número "))
b = (input("insira o segundo número "))
c = (input("insira o terceiro número "))
if a > b and a > c:
  print(a)
elif b > a and b > c:
  print(b)
else:
  print(c)

a = (input("insira o primeiro numero "))
b = (input("insira o segundo numero "))
c = (input("insira o terceiro numero "))
if a > b and a > c:
 maior=a
elif b > a and b > c:
 maior=b
else:
 maior=c
print("O maior numero é",maior)
if a < b and a < c:
  menor=a
elif b < a and b < c:
  menor=b
else:
  menor=c
print("O menor numero é",menor)

a = float(input("insira o preço do primeiro produto "))
b = float(input("insira o preço do segundo produto "))
c = float(input("insira o preço do terceiro produto "))
if a < b and a < c:
  menor=a
elif b < a and b < c:
  menor=b
else:
  menor=c
print("O produto com o menor preço é:",menor)

a = int(input("insira o primeiro numero "))
b = int(input("insira o segundo numero "))
c = int(input("insira o terceiro numero "))
if a >= b and a >= c and b >= c:
  print("Numero decrescente",a,b,c)
elif a >= b and a >= c and c >= b:
  print("Numero decrescente",a,c,b)
elif b >= a and b >= c and a >= c:
  print("Numero decrescente",b,a,c)
elif b >= a and b >= c and c >= a:
  print("Numero decrescente",b,c,a)
elif c >= a and c >= b and a >= b:
  print("Numero decrescente",c,a,b)
elif c >= a and c >= b and b >= a:
  print("Numero decrescente",c,b,a)

a = input("insira o seu turno de estudo,se for Matutino escreva M ou m, se for Vespertino escreva V ou v, e se for Noturno escreva N ou n: ")
if a == "M" or a == "m":
  print("Bom dia!")
elif a == "V" or a == "v":
  print("Boa tarde!")
elif a == "N" or a == "n":
  print("Boa noite!")
else:
  print("Valor inválido")

num1 = int(input("insira o primeiro numero "))
num2 = int(input("insira o segundo numero "))
if num1 > num2:
  maior=num1
  menor=num2
else:
  maior=num2
  menor=num1
  print("O maior numero é",maior)
  print("O menor numero é",menor)

num = int(input("insira um numero de 1 a 7: "))
if num == 1:
  print("O dia da semana é 1-domingo")
elif num == 2:
  print("O dia da semana é 2-segunda")
elif num == 3:
  print("O dia da semana é 3-terça-feira")
elif num == 4:
  print("O dia da semana é 4-quarta-feira")
elif num == 5:
  print("O dia da semana é 5-quinta-feira")
elif num == 6:
  print("O dia da semana é 6-sexta-feira")
elif num == 7:
  print("O dia da semana é 7-sabádo")
else:
  print("Valor inválido")